server:
  port: 8080

spring:
  application:
    name: base
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: src/main/resources/mapper/*.xml